# Generated by Django 5.1.3 on 2024-11-27 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='crm.company')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryCertificate',
            fields=[
                ('certificate_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('delivery_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='rentals.contract')),
            ],
        ),
    ]
