# Generated by Django 3.1.12 on 2024-11-26 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('nit', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('creation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_interaction_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.company')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('inventory_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('acquisition_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('opportunity_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('opportunity_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estimated_close_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('success_probability', models.DecimalField(decimal_places=2, max_digits=6)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.contact')),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityStage',
            fields=[
                ('stage_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stage_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductService',
            fields=[
                ('product_service_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('product_service_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('nit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.company')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityStageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.opportunity')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.opportunitystage')),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityProductService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('negotiated_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.opportunity')),
                ('product_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.productservice')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryCertificate',
            fields=[
                ('certificate_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('delivery_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.contract')),
            ],
        ),
    ]
