# Generated by Django 3.1.12 on 2024-11-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
